raw<-read.table("household_power_consumption.txt",sep=";")
tidy<-data.frame(rbind(raw[raw[,1]=="1/2/2007",],raw[raw[,1]=="2/2/2007",]))
png("plot4.png",width=480,height=480)
par(mfrow=c(2,2),mar=c(4,4,2,2))
plot(as.numeric(as.character(tidy$V3)),type="l",ylab="Global Acitve Power(kilowatts)")
plot(as.numeric(as.character(tidy$V5)),type="l",ylab="Voltage")
plot(as.numeric(as.character(tidy[,7])),type="l",ylab="Energy Sub Metering")
lines(as.numeric(as.character(tidy[,8])),type="l",ylab="Energy Sub Metering",col="red")
lines(as.numeric(as.character(tidy[,9])),type="l",ylab="Energy Sub Metering",col="blue")
legend("topright",pch="-",col=c("black","red","blue"),legend=c("Sub_Metering_1","Sub_Metering_2","Sub_Metering_3"))
plot(as.numeric(as.character(tidy$V4)),type="l",ylab="Global Reactive Power")
dev.off()