raw<-read.table("household_power_consumption.txt",sep=";")
tidy<-data.frame(rbind(raw[raw[,1]=="1/2/2007",],raw[raw[,1]=="2/2/2007",]))
png("plot1.png",width=480,height=480)
hist(as.numeric(tidy$V3),col="red",main="Global Active Power",xlab="Global Acitve Power (kilowatts)")
dev.off()
